In [1]:
from pathlib import Path
import sys

print('Python 실행 파일:', sys.executable)
print("현재 작업 폴더:", Path.cwd())

Python 실행 파일: c:\dev\llm-data-analysis-course\.venv\Scripts\python.exe
현재 작업 폴더: c:\dev\llm-data-analysis-course\notebooks

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

PROJECT_ROOT = Path.cwd()

if not (PROJECT_ROOT / "data" / "raw").exists() and (PROJECT_ROOT.parent / "data" / "raw").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "raw"

sns.set_theme(style="whitegrid")

print("프로젝트 루트:", PROJECT_ROOT)
print("데이터 폴더:", DATA_DIR)
print("데이터 폴더 존재 여부:", DATA_DIR.exists())

프로젝트 루트: c:\dev\llm-data-analysis-course
데이터 폴더: c:\dev\llm-data-analysis-course\data\raw
데이터 폴더 존재 여부: True

In [7]:
df_customers = pd.read_csv(DATA_DIR/ "customers.csv")

print(type(DATA_DIR))

df_customers.info()

<class 'pathlib.WindowsPath'>
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  150 non-null    int64
 1   name         150 non-null    str
 2   gender       150 non-null    str
 3   age          150 non-null    int64
 4   city         150 non-null    str
 5   signup_date  150 non-null    str
dtypes: int64(2), str(4)
memory usage: 7.2 KB

In [8]:
columns = df_customers.columns.tolist()

for col in columns:
    print(col)

customer_id
name
gender
age
city
signup_date

In [9]:
customers = df_customers.copy()

In [11]:
customers_over_30 = customers[customers["age"]>=30]

print(customers_over_30.head())
print(customers_over_30.info())

   customer_id name gender  age city signup_date
1            2  김정호      F   32   대구  2025-12-28
2            3  이경수      F   61   성남  2024-08-07
3            4  조영호      F   55   울산  2026-06-08
5            6  김지원      F   32   성남  2026-08-22
6            7  이상현      F   53   인천  2025-02-06
<class 'pandas.DataFrame'>
Index: 111 entries, 1 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  111 non-null    int64
 1   name         111 non-null    str
 2   gender       111 non-null    str
 3   age          111 non-null    int64
 4   city         111 non-null    str
 5   signup_date  111 non-null    str
dtypes: int64(2), str(4)
memory usage: 6.1 KB
None

In [12]:
customers["city"].value_counts(dropna=False)

city
성남    21
광주    17
부산    16
대구    15
서울    15
울산    14
인천    14
대전    14
수원    13
고양    11
Name: count, dtype: int64

In [14]:
customers.sort_values("age",ascending=False).head()

     customer_id name gender  age city signup_date
14            15  장정식      M   69   서울  2026-07-30
8              9  송지민      M   69   서울  2025-12-14
54            55  윤영철      M   69   광주  2023-09-25
78            79  이서준      M   69   부산  2023-09-08
136          137  김선영      M   68   울산  2025-01-23

In [16]:
customers_work = customers.copy()

customers_work["grade"] = 'VIP'

customers_work.head()

   customer_id name gender  age city signup_date grade
0            1  김수민      F   19   광주  2024-08-14   VIP
1            2  김정호      F   32   대구  2025-12-28   VIP
2            3  이경수      F   61   성남  2024-08-07   VIP
3            4  조영호      F   55   울산  2026-06-08   VIP
4            5  이예원      F   19   부산  2024-11-08   VIP

환경 확인과 4개 csv 불러오기
-customers
-orders

In [2]:
from course_utils.paths import get_project_root, get_data_dir
import pandas as pd

#print(get_data_dir())

customers = pd.read_csv(get_data_dir() / "raw/customers.csv")
orders = pd.read_csv(get_data_dir() / "raw/orders.csv")

print(customers.info())
print(orders.info())

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  150 non-null    int64
 1   name         150 non-null    str
 2   gender       150 non-null    str
 3   age          150 non-null    int64
 4   city         150 non-null    str
 5   signup_date  150 non-null    str
dtypes: int64(2), str(4)
memory usage: 7.2 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        300 non-null    int64
 1   customer_id     300 non-null    int64
 2   order_date      300 non-null    str
 3   payment_method  300 non-null    str
 4   order_status    300 non-null    str
dtypes: int64(2), str(3)
memory usage: 11.8 KB
None

In [4]:
#products
#order_items

print(orders.head())

   order_id  customer_id  order_date payment_method order_status
0         1          123  2026-07-02           card    completed
1         2           77  2025-09-17      naver_pay    cancelled
2         3          138  2026-01-14  bank_transfer    cancelled
3         4           57  2026-03-27      kakao_pay    cancelled
4         5          125  2026-02-15           card    cancelled

In [7]:
#주문 상태의 종류는 몇가지이고 각 상태별 주문 수량?
ret = orders["order_status"].value_counts(dropna=False)
print(type(ret))
print(ret)

# 결제 수단의 종류는 몇가지이고 각 결제 상태별 주문수량?

print(orders["payment_method"].value_counts(dropna=False))

<class 'pandas.Series'>
order_status
completed    184
cancelled     64
refunded      52
Name: count, dtype: int64
payment_method
kakao_pay        79
naver_pay        77
bank_transfer    74
card             70
Name: count, dtype: int64

In [12]:
#customers_over_30
customers["age"] >=30

#불리언마스크 customers[조건식]

customers_over_30 = customers[customers["age"] >= 30]
print(customers_over_30)
type(customers_over_30)

     customer_id name gender  age city signup_date
1              2  김정호      F   32   대구  2025-12-28
2              3  이경수      F   61   성남  2024-08-07
3              4  조영호      F   55   울산  2026-06-08
5              6  김지원      F   32   성남  2026-08-22
6              7  이상현      F   53   인천  2025-02-06
..           ...  ...    ...  ...  ...         ...
141          142  하서연      F   32   서울  2023-10-04
142          143  김예은      F   43   대전  2024-02-27
144          145  조정호      M   59   성남  2024-02-27
145          146  김숙자      M   61   성남  2026-02-17
149          150  조미영      M   40   대전  2026-01-29

[111 rows x 6 columns]

pandas.DataFrame

In [13]:
print(customers_over_30["age"].max())
print(customers_over_30["age"].min())

69
30

In [14]:
print(customers_over_30.describe())

       customer_id         age
count   111.000000  111.000000
mean     74.171171   48.711712
std      43.773773   12.504826
min       2.000000   30.000000
25%      35.500000   35.500000
50%      73.000000   50.000000
75%     113.500000   60.000000
max     150.000000   69.000000

In [18]:
#도시별 회원수
print(customers["city"].value_counts(dropna=False))

city
성남    21
광주    17
부산    16
대구    15
서울    15
울산    14
인천    14
대전    14
수원    13
고양    11
Name: count, dtype: int64

In [16]:
print(customers["city"].unique())

<StringArray>
['광주', '대구', '성남', '울산', '부산', '인천', '수원', '서울', '대전', '고양']
Length: 10, dtype: str

In [19]:
#서울, 부산, 인천 도시의 고객들은 누구인가? &, ㅣ, ~ 

city_customers = customers[customers["city"].isin(["서울", "부산", "인천"])]
print(city_customers.head(10))

    customer_id name gender  age city signup_date
4             5  이예원      F   19   부산  2024-11-08
6             7  이상현      F   53   인천  2025-02-06
8             9  송지민      M   69   서울  2025-12-14
14           15  장정식      M   69   서울  2026-07-30
15           16  강보람      M   52   부산  2024-09-17
18           19  김성수      M   54   인천  2024-10-22
19           20  백영호      F   20   인천  2025-01-03
20           21  박중수      M   23   인천  2026-05-28
29           30  이민재      F   32   서울  2023-09-08
39           40  박예준      M   23   서울  2024-07-28

In [20]:
print(city_customers["city"].value_counts())

city
부산    16
서울    15
인천    14
Name: count, dtype: int64

In [22]:
#컬럼 추가(파생 컬럼)
#라인 합계 금액: line_total = quantity * unit_price
# print(order_items.info())
order_items["line_total"] = order_items["quantity"] * order_items["unit_price"]

print(order_items.head(10))

   order_item_id  order_id  product_id  quantity  unit_price  line_total
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000
5              6         3          33         5      124000      620000
6              7         3          20         3       80000      240000
7              8         3          11         5      115000      575000
8              9         4          45         3       62000      186000
9             10         4          84         4       78000      312000

In [24]:
print(orders["order_id"].duplicated().sum())

0

In [ ]:
#print(order_items.head())
#order_status를 함께 출력 하려면 => merge

order_sales = order_items.merge(
    orders[["order_id","customer_id","order_date","order_status"]],
    on="order_id", how="left", validate="many_to_one"
)

print(order_sales.head())

   order_item_id  order_id  product_id  quantity  unit_price  line_total  \
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

   customer_id  order_date order_status
0          123  2026-07-02    completed
1          123  2026-07-02    completed
2          123  2026-07-02    completed
3          123  2026-07-02    completed
4           77  2025-09-17    cancelled

In [28]:
print(orders.info())

print(orders["order_date"].dtype)

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        300 non-null    int64
 1   customer_id     300 non-null    int64
 2   order_date      300 non-null    str
 3   payment_method  300 non-null    str
 4   order_status    300 non-null    str
dtypes: int64(2), str(3)
memory usage: 11.8 KB
None
str

In [31]:
order_sales_test = order_sales.copy()

print(order_sales_test.info())

<class 'pandas.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  764 non-null    int64
 1   order_id       764 non-null    int64
 2   product_id     764 non-null    int64
 3   quantity       764 non-null    int64
 4   unit_price     764 non-null    int64
 5   line_total     764 non-null    int64
 6   customer_id    764 non-null    int64
 7   order_date     764 non-null    str
 8   order_status   764 non-null    str
dtypes: int64(7), str(2)
memory usage: 53.8 KB
None

In [32]:
order_sales_test["order_date"] = pd.to_datetime(
    order_sales_test["order_date"]
)

print(order_sales_test.info())

<class 'pandas.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  764 non-null    int64
 1   order_id       764 non-null    int64
 2   product_id     764 non-null    int64
 3   quantity       764 non-null    int64
 4   unit_price     764 non-null    int64
 5   line_total     764 non-null    int64
 6   customer_id    764 non-null    int64
 7   order_date     764 non-null    datetime64[us]
 8   order_status   764 non-null    str
dtypes: datetime64[us](1), int64(7), str(1)
memory usage: 53.8 KB
None

In [33]:
order_sales_test2= order_sales.copy()
print(order_sales_test2.head())

   order_item_id  order_id  product_id  quantity  unit_price  line_total  \
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

   customer_id  order_date order_status
0          123  2026-07-02    completed
1          123  2026-07-02    completed
2          123  2026-07-02    completed
3          123  2026-07-02    completed
4           77  2025-09-17    cancelled

In [34]:
order_sales_test2.loc[0, "order_date"] ="2026-02-30"

In [40]:
order_sales_test2["order_date"] = pd.to_datetime(
    order_sales_test2["order_date"],
    errors="coerce"
)

print(order_sales_test2.info())

print(order_sales_test2.head(5))
print(order_sales_test2["order_date"].isna().sum())

<class 'pandas.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  764 non-null    int64
 1   order_id       764 non-null    int64
 2   product_id     764 non-null    int64
 3   quantity       764 non-null    int64
 4   unit_price     764 non-null    int64
 5   line_total     764 non-null    int64
 6   customer_id    764 non-null    int64
 7   order_date     763 non-null    datetime64[us]
 8   order_status   764 non-null    str
dtypes: datetime64[us](1), int64(7), str(1)
memory usage: 53.8 KB
None
   order_item_id  order_id  product_id  quantity  unit_price  line_total  \
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

   customer_id order_date order_status
0          123        NaT    completed
1          123 2026-07-02    completed
2          123 2026-07-02    completed
3          123 2026-07-02    completed
4           77 2025-09-17    cancelled
1

In [39]:
order_sales_test2.head(5)

,order_item_id,order_id,product_id,quantity,unit_price,line_total,customer_id,order_date,order_status
0,1,1,100,3,102000,306000,123,NaT,completed
1,2,1,87,5,25000,125000,123,2026-07-02,completed
2,3,1,7,3,142000,426000,123,2026-07-02,completed
3,4,1,9,3,193000,579000,123,2026-07-02,completed
4,5,2,72,4,189000,756000,77,2025-09-17,cancelled

In [43]:
order_sales_test2= order_sales_test2.dropna()
print(order_sales_test2["order_date"].isna().sum())

0

In [51]:
#파생 컬럼 order_month 추가하고 0으로 초기화

order_sales_test2["order_month"] = order_sales_test2["order_date"].dt.to_period("M").astype(str)

In [49]:
print(order_sales_test2.head())

   order_item_id  order_id  product_id  quantity  unit_price  line_total  \
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000
5              6         3          33         5      124000      620000

   customer_id order_date order_status order_month
1          123 2026-07-02    completed     2026-07
2          123 2026-07-02    completed     2026-07
3          123 2026-07-02    completed     2026-07
4           77 2025-09-17    cancelled     2025-09
5          138 2026-01-14    cancelled     2026-01