In [1]:
from pathlib import Path
import sys

import pandas as pd
import numpy as np

# 프로젝트 루트와 notebooks 폴더 어느 곳에서 실행해도 경로를 찾습니다.
project_root = next(
    (path for path in (Path.cwd(), *Path.cwd().parents)
     if (path / "src" / "processing.py").is_file()
     and (path / "data" / "raw").is_dir()),
    None,
)
if project_root is None:
    raise FileNotFoundError("프로젝트 폴더 또는 notebooks 폴더에서 실행해 주세요.")
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

data_dir = project_root / "data" / "raw"
customers = pd.read_csv(data_dir / "customers.csv")
orders = pd.read_csv(data_dir / "orders.csv")
order_items = pd.read_csv(data_dir / "order_items.csv")
products = pd.read_csv(data_dir / "products.csv")

print(customers.head())
print(orders.head())
print(order_items.head())
print(products.head())

   customer_id name gender  age city signup_date
0            1  김수민      F   19   광주  2024-08-14
1            2  김정호      F   32   대구  2025-12-28
2            3  이경수      F   61   성남  2024-08-07
3            4  조영호      F   55   울산  2026-06-08
4            5  이예원      F   19   부산  2024-11-08
   order_id  customer_id  order_date payment_method order_status
0         1          123  2026-07-02           card    completed
1         2           77  2025-09-17      naver_pay    cancelled
2         3          138  2026-01-14  bank_transfer    cancelled
3         4           57  2026-03-27      kakao_pay    cancelled
4         5          125  2026-02-15           card    cancelled
   order_item_id  order_id  product_id  quantity  unit_price
0              1         1         100         3      102000
1              2         1          87         5       25000
2              3         1           7         3      142000
3              4         1           9         3      193000
4              5         2          72         4      189000
   product_id product_name category   price
0           1  전자기기 상품 001     전자기기  160000
1           2    도서 상품 002       도서   34000
2           3  전자기기 상품 003     전자기기  152000
3           4  생활용품 상품 004     생활용품   70000
4           5    식품 상품 005       식품  186000

In [2]:
#원본 구조 Evidence를 만든다.
raw_data= {"customers": customers, "order_items": order_items ,"products": products,"orders": orders}
print(raw_data)

{'customers':      customer_id name gender  age city signup_date
0              1  김수민      F   19   광주  2024-08-14
1              2  김정호      F   32   대구  2025-12-28
2              3  이경수      F   61   성남  2024-08-07
3              4  조영호      F   55   울산  2026-06-08
4              5  이예원      F   19   부산  2024-11-08
..           ...  ...    ...  ...  ...         ...
145          146  김숙자      M   61   성남  2026-02-17
146          147  이정남      M   19   부산  2025-04-08
147          148  오도현      M   29   고양  2026-08-10
148          149  김정자      M   20   부산  2024-12-14
149          150  조미영      M   40   대전  2026-01-29

[150 rows x 6 columns], 'order_items':      order_item_id  order_id  product_id  quantity  unit_price
0                1         1         100         3      102000
1                2         1          87         5       25000
2                3         1           7         3      142000
3                4         1           9         3      193000
4                5         2          72         4      189000
..             ...       ...         ...       ...         ...
759            760       297          42         4       28000
760            761       298          40         4      174000
761            762       299           8         2      189000
762            763       299          12         4      175000
763            764       300          59         5       32000

[764 rows x 5 columns], 'products':     product_id product_name category   price
0            1  전자기기 상품 001     전자기기  160000
1            2    도서 상품 002       도서   34000
2            3  전자기기 상품 003     전자기기  152000
3            4  생활용품 상품 004     생활용품   70000
4            5    식품 상품 005       식품  186000
..         ...          ...      ...     ...
95          96  생활용품 상품 096     생활용품  112000
96          97  전자기기 상품 097     전자기기  154000
97          98   스포츠 상품 098      스포츠   10000
98          99    뷰티 상품 099       뷰티  200000
99         100    도서 상품 100       도서  102000

[100 rows x 4 columns], 'orders':      order_id  customer_id  order_date payment_method order_status
0           1          123  2026-07-02           card    completed
1           2           77  2025-09-17      naver_pay    cancelled
2           3          138  2026-01-14  bank_transfer    cancelled
3           4           57  2026-03-27      kakao_pay    cancelled
4           5          125  2026-02-15           card    cancelled
..        ...          ...         ...            ...          ...
295       296          116  2026-03-30           card    completed
296       297           22  2026-03-12  bank_transfer    completed
297       298           64  2026-02-19      naver_pay    cancelled
298       299          135  2025-10-03  bank_transfer    completed
299       300           96  2026-04-22      kakao_pay    cancelled

[300 rows x 5 columns]}

In [3]:
summary_list = []
for name, frame in raw_data.items():
    info = {
        "dataset": name,
        "rows": len(frame),
        "clums":frame.shape[1],
        "missing_valus":frame.isna().sum(),
        "duplicated_rows":frame.duplicated().sum(),
    }
    summary_list.append(info)

In [4]:
summary_list

[{'dataset': 'customers',
  'rows': 150,
  'clums': 6,
  'missing_valus': customer_id    0
  name           0
  gender         0
  age            0
  city           0
  signup_date    0
  dtype: int64,
  'duplicated_rows': np.int64(0)},
 {'dataset': 'order_items',
  'rows': 764,
  'clums': 5,
  'missing_valus': order_item_id    0
  order_id         0
  product_id       0
  quantity         0
  unit_price       0
  dtype: int64,
  'duplicated_rows': np.int64(0)},
 {'dataset': 'products',
  'rows': 100,
  'clums': 4,
  'missing_valus': product_id      0
  product_name    0
  category        0
  price           0
  dtype: int64,
  'duplicated_rows': np.int64(0)},
 {'dataset': 'orders',
  'rows': 300,
  'clums': 5,
  'missing_valus': order_id          0
  customer_id       0
  order_date        0
  payment_method    0
  order_status      0
  dtype: int64,
  'duplicated_rows': np.int64(0)}]

In [5]:
# 이 셀만 실행해도 프로젝트 모듈을 찾도록 경로를 설정합니다.
from pathlib import Path
import sys

project_root = next(
    (path for path in (Path.cwd(), *Path.cwd().parents)
     if (path / "src" / "processing.py").is_file()),
    None,
)
if project_root is None:
    raise FileNotFoundError(f"현재 폴더({Path.cwd()})에서 프로젝트를 찾지 못했습니다.")
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.processing import (
    compare_shapes,
    preprocess_sales_data,
    validate_relationships,
)

processed_data = preprocess_sales_data(raw_data)
preprocessing_comparison = compare_shapes(raw_data, processed_data)
relationship_checks = validate_relationships(processed_data)

In [6]:
display(preprocessing_comparison)
display(relationship_checks)

       dataset  rows_raw  columns_raw  rows_processed  columns_processed
0    customers       150            6             150                  6
1  order_items       764            5             764                  6
2       orders       300            5             300                  7
3     products       100            4             100                  4

                                               check  invalid_count
0  orders.customer_id exists in customers.custome...              0
1     order_items.order_id exists in orders.order_id              0
2  order_items.product_id exists in products.prod...              0

In [7]:
print(processed_data["orders"].head())

   order_id  customer_id order_date payment_method order_status order_month  \
0         1          123 2026-07-02           card    completed     2026-07
1         2           77 2025-09-17      naver_pay    cancelled     2025-09
2         3          138 2026-01-14  bank_transfer    cancelled     2026-01
3         4           57 2026-03-27      kakao_pay    cancelled     2026-03
4         5          125 2026-02-15           card    cancelled     2026-02

  order_dayofweek
0        Thursday
1       Wednesday
2       Wednesday
3          Friday
4          Sunday

In [8]:
# 각 데이터셋에서 기본 키로 사용할 컬럼
key_map = {
    "customers": "customer_id",
    "products": "product_id",
    "orders": "order_id",
    "order_items": "order_item_id",
}

key_checks = []

for dataset, key in key_map.items():
    frame = processed_data[dataset]
    missing_count = int(frame[key].isna().sum())
    duplicated_count = int(frame[key].duplicated().sum())

    key_checks.append({
        "dataset": dataset,
        "key": key,
        "missing_count": missing_count,
        "duplicated_count": duplicated_count,
    })

key_checks_df = pd.DataFrame(key_checks)
display(key_checks_df)

       dataset            key  missing_count  duplicated_count
0    customers    customer_id              0                 0
1     products     product_id              0                 0
2       orders       order_id              0                 0
3  order_items  order_item_id              0                 0

In [9]:
# 주문 상세와 주문 정보를 결합하고 주문 항목별 매출액을 추가합니다.
order_sales = processed_data["order_items"].merge(
    processed_data["orders"][[
        "order_id", "customer_id", "order_date", "order_status"
    ]],
    on="order_id",
    how="left",
    validate="many_to_one",
)

# 전처리 결과에 line_total이 없을 때도 계산되도록 보장합니다.
order_sales["line_total"] = (
    order_sales["quantity"] * order_sales["unit_price"]
)

display(order_sales.head())

,order_item_id,order_id,product_id,quantity,unit_price,line_total,customer_id,order_date,order_status
0,1,1,100,3,102000,306000,123,2026-07-02,completed
1,2,1,87,5,25000,125000,123,2026-07-02,completed
2,3,1,7,3,142000,426000,123,2026-07-02,completed
3,4,1,9,3,193000,579000,123,2026-07-02,completed
4,5,2,72,4,189000,756000,77,2025-09-17,cancelled

In [ ]:
import pandas as pd
import numpy as np

data_dir = "../data/raw"

customers = pd.read_csv(data_dir / "customers.csv")
orders = pd.read_csv(data_dir / "orders.csv")
order_items = pd.read_csv(data_dir / "order_items.csv")
products = pd.read_csv(data_dir / "products.csv")

print(customers.head())
print(orders.head())
print(order_items.head())
print(products.head())